'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class LeaveApprovalForm
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AccuPay.LeaveApprovalForm", GetType(LeaveApprovalForm).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property Checked_UserAddedColumn() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("Checked.UserAddedColumn", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property Comment_UserAddedColumn() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("Comment.UserAddedColumn", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property EmployeeID_UserAddedColumn() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("EmployeeID.UserAddedColumn", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property EmployeeName_UserAddedColumn() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("EmployeeName.UserAddedColumn", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property EndDate_UserAddedColumn() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("EndDate.UserAddedColumn", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property LeaveType_UserAddedColumn() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("LeaveType.UserAddedColumn", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property Reason_UserAddedColumn() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("Reason.UserAddedColumn", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property RowID_UserAddedColumn() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("RowID.UserAddedColumn", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property StartDate_UserAddedColumn() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("StartDate.UserAddedColumn", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property Status_UserAddedColumn() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("Status.UserAddedColumn", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
    End Class
End Namespace
