namespace AccuPay.Data
{
    public interface IPaystubPayslipModel
    {
        decimal AbsentAmount { get; }
        decimal AbsentHours { get; }
        string AdjustmentAmountsSummary { get; }
        string AdjustmentNamesSummary { get; }
        decimal Allowance { get; }
        decimal BasicHours { get; }
        decimal BasicPay { get; }
        decimal Ecola { get; }
        int EmployeeId { get; }
        string EmployeeName { get; }
        string EmployeeNumber { get; }
        decimal GrossPay { get; }
        decimal LateAndUndertimeAmount { get; }
        decimal LateAndUndertimeHours { get; }
        decimal LeaveHours { get; }
        decimal LeavePay { get; }
        string LoanAmountsSummary { get; }
        string LoanBalancesSummary { get; }
        string LoanNamesSummary { get; }
        decimal NetPay { get; }
        decimal NightDiffHours { get; }
        decimal NightDiffOvertimeHours { get; }
        decimal NightDiffOvertimePay { get; }
        decimal NightDiffPay { get; }
        string OvertimeAmountsSummary { get; }
        decimal OvertimeHours { get; }
        string OvertimeHoursSummary { get; }
        string OvertimeNamesSummary { get; }
        decimal OvertimePay { get; }
        decimal PagibigAmount { get; }
        decimal PhilHealthAmount { get; }
        decimal RegularHolidayHours { get; }
        decimal RegularHolidayNightDiffHours { get; }
        decimal RegularHolidayNightDiffOTHours { get; }
        decimal RegularHolidayNightDiffOTPay { get; }
        decimal RegularHolidayNightDiffPay { get; }
        decimal RegularHolidayOTHours { get; }
        decimal RegularHolidayOTPay { get; }
        decimal RegularHolidayPay { get; }
        decimal RegularHolidayRestDayHours { get; }
        decimal RegularHolidayRestDayNightDiffHours { get; }
        decimal RegularHolidayRestDayNightDiffOTHours { get; }
        decimal RegularHolidayRestDayNightDiffOTPay { get; }
        decimal RegularHolidayRestDayNightDiffPay { get; }
        decimal RegularHolidayRestDayOTHours { get; }
        decimal RegularHolidayRestDayOTPay { get; }
        decimal RegularHolidayRestDayPay { get; }
        decimal RegularPay { get; }
        decimal RestDayHours { get; }
        decimal RestDayNightDiffHours { get; }
        decimal RestDayNightDiffOTHours { get; }
        decimal RestDayNightDiffOTPay { get; }
        decimal RestDayNightDiffPay { get; }
        decimal RestDayOTHours { get; }
        decimal RestDayOTPay { get; }
        decimal RestDayPay { get; }
        decimal SpecialHolidayHours { get; }
        decimal SpecialHolidayNightDiffHours { get; }
        decimal SpecialHolidayNightDiffOTHours { get; }
        decimal SpecialHolidayNightDiffOTPay { get; }
        decimal SpecialHolidayNightDiffPay { get; }
        decimal SpecialHolidayOTHours { get; }
        decimal SpecialHolidayOTPay { get; }
        decimal SpecialHolidayPay { get; }
        decimal SpecialHolidayRestDayHours { get; }
        decimal SpecialHolidayRestDayNightDiffHours { get; }
        decimal SpecialHolidayRestDayNightDiffOTHours { get; }
        decimal SpecialHolidayRestDayNightDiffOTPay { get; }
        decimal SpecialHolidayRestDayNightDiffPay { get; }
        decimal SpecialHolidayRestDayOTHours { get; }
        decimal SpecialHolidayRestDayOTPay { get; }
        decimal SpecialHolidayRestDayPay { get; }
        decimal SSSAmount { get; }
        decimal TaxWithheldAmount { get; }
        decimal TotalAdjustments { get; }
        decimal TotalDeductions { get; }
        decimal TotalLoans { get; }
        decimal TotalOvertimeHours { get; }
        decimal TotalOvertimePay { get; }
    }
}