ALTER TABLE `employeetimeentrydetails`
	ADD COLUMN `LunchOut` TIME NULL DEFAULT NULL AFTER `TimeIn`,
	ADD COLUMN `LunchIn` TIME NULL DEFAULT NULL AFTER `LunchOut`,
	ADD COLUMN `TimeStampLunchOut` DATETIME NULL DEFAULT NULL AFTER `TimeStampIn`,
	ADD COLUMN `TimeStampLunchIn` DATETIME NULL DEFAULT NULL AFTER `TimeStampLunchOut`;
