/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP TABLE IF EXISTS `shiftschedules`;
CREATE TABLE IF NOT EXISTS `shiftschedules` (
	`RowID` INT(10) NOT NULL AUTO_INCREMENT,
	`OrganizationID` INT(10) NULL DEFAULT NULL,
	`Created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`CreatedBy` INT(10) NULL DEFAULT NULL,
	`LastUpd` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`LastUpdBy` INT(10) NULL DEFAULT NULL,
	`EmployeeID` INT(10) NULL DEFAULT NULL,
	`Date` DATE NOT NULL,
	`StartTime` TIME NULL DEFAULT NULL,
	`EndTime` TIME NULL DEFAULT NULL,
	`BreakStartTime` TIME NULL DEFAULT NULL,
	`BreakLength` DECIMAL(10,2) NULL DEFAULT '0',
	`IsRestDay` TINYINT(1) NOT NULL DEFAULT '0',
	`ShiftHours` DECIMAL(10,2) NULL DEFAULT '0',
	PRIMARY KEY (`RowID`),
	UNIQUE INDEX `AK_EmployeeID_Date` (`EmployeeID`, `Date`),
	INDEX `FK_shiftschedules_organization_OrganizationID` (`OrganizationID`),
	INDEX `FK_shiftschedules_user_CreatedBy` (`CreatedBy`),
	INDEX `FK_shiftschedules_user_LastUpdBy` (`LastUpdBy`),
	CONSTRAINT `FK_shiftschedules_organization_OrganizationID` FOREIGN KEY (`OrganizationID`) REFERENCES `organization` (`RowID`) ON DELETE SET NULL,
	CONSTRAINT `FK_shiftschedules_user_CreatedBy` FOREIGN KEY (`CreatedBy`) REFERENCES `user` (`RowID`) ON DELETE SET NULL,
	CONSTRAINT `FK_shiftschedules_user_LastUpdBy` FOREIGN KEY (`LastUpdBy`) REFERENCES `user` (`RowID`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=8243 DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
