/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `account` (
  `RowID` int(10) NOT NULL AUTO_INCREMENT,
  `CompanyName` varchar(100) DEFAULT NULL COMMENT 'Registered/Formal Customer name in BIR',
  `TradeName` varchar(100) DEFAULT NULL COMMENT 'Customer Company Name used outside ',
  `MobilePhone` varchar(100) DEFAULT NULL,
  `OrganizationID` int(11) DEFAULT NULL COMMENT 'Internal Company',
  `AccountNo` int(11) NOT NULL COMMENT 'Account number of the Company',
  `PrimaryContactID` int(11) DEFAULT NULL COMMENT 'Primary Contact of the Account',
  `PrimaryAddressID` int(11) DEFAULT NULL COMMENT 'Links to Address table.  Primary address of Account',
  `PrimaryBillToAddressID` int(11) DEFAULT NULL,
  `PrimarySoldToAddressID` int(11) DEFAULT NULL,
  `PrimaryShipToAddressID` int(11) DEFAULT NULL,
  `PrimaryAgreementID` int(11) DEFAULT NULL COMMENT 'Contract ID',
  `PrimaryBillToPersonID` int(11) DEFAULT NULL,
  `PrimaryShipToPersonID` int(11) DEFAULT NULL,
  `PrimarySoldToPersonID` int(11) DEFAULT NULL,
  `ParentAccountID` int(11) DEFAULT NULL COMMENT 'Links to Account.  If company has branch, then the parentaccountID should be used to link',
  `VATRegistrationNo` varchar(50) DEFAULT NULL COMMENT 'TIN Number',
  `ATPNo` varchar(50) DEFAULT NULL,
  `AccountType` varchar(50) NOT NULL COMMENT 'Branch,Main,Retail,Supplier,Bank,Tenant',
  `BranchFlg` varchar(50) DEFAULT NULL COMMENT 'If the Account is a branch, this flag should be checked',
  `BusinessType` varchar(50) DEFAULT NULL COMMENT 'Sole Propriator, Corporation, Partnership',
  `PrimaryHomeAddressID` int(11) unsigned zerofill DEFAULT NULL COMMENT 'Primary Home Address ID of contact (if sole proprietor)',
  `FloorArea` decimal(10,2) DEFAULT '0.00' COMMENT 'Used by Royal Metropointe for informational purpose to track tenant''s other businesses',
  `AverageMonthlySales` decimal(10,2) DEFAULT '0.00' COMMENT 'Average Monthly Sales of the branch',
  `YearsInBusiness` decimal(10,2) DEFAULT '0.00' COMMENT 'Years in Business of the branch',
  `ExistingBranch` varchar(1) DEFAULT NULL COMMENT 'If With Existing Branch, then Y. if Without Existing Branch, then N',
  `FaxNumber` varchar(50) DEFAULT NULL,
  `Description` varchar(1000) DEFAULT NULL COMMENT 'Description of the nature of business',
  `Active` char(1) DEFAULT NULL COMMENT 'If account is active, then Y',
  `ManagerName` varchar(50) DEFAULT NULL COMMENT 'Manager Name of the account',
  `PaymentTermsID` int(11) DEFAULT NULL,
  `BranchType` varchar(50) DEFAULT NULL COMMENT 'Type of Branch',
  `AliasName` varchar(100) DEFAULT NULL COMMENT 'Other name of the Account',
  `CustomerSinceDate` date DEFAULT NULL COMMENT 'When this customer started doing business with Organization',
  `CreditDays` int(11) DEFAULT NULL COMMENT 'Credit Days',
  `StockHolder1` varchar(100) DEFAULT NULL COMMENT 'for Royal MP to track stockholders if corporation business type',
  `StockHolder2` varchar(100) DEFAULT NULL COMMENT 'for Royal MP to track stockholders if corporation business type',
  `StockHolder3` varchar(100) DEFAULT NULL COMMENT 'for Royal MP to track stockholders if corporation business type',
  `Comments` varchar(2000) DEFAULT NULL COMMENT 'General Comments about Customer',
  `GoodStandingFlg` char(1) DEFAULT NULL,
  `Created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LastUpd` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `CreatedBy` int(11) NOT NULL,
  `LastUpdBy` int(11) NOT NULL,
  `PrimaryRepID` int(11) DEFAULT NULL COMMENT 'Primary Representative of the Account',
  `EmailAddress` varchar(100) DEFAULT NULL,
  `AltEmailAddress` varchar(100) DEFAULT NULL,
  `Website` varchar(100) DEFAULT NULL,
  `MainPhone` varchar(100) DEFAULT NULL,
  `AltPhone` varchar(100) DEFAULT NULL,
  `Status` varchar(50) DEFAULT NULL COMMENT 'Prospect,Active',
  `Capitalization` decimal(10,2) DEFAULT NULL,
  `AverageRating` decimal(10,2) DEFAULT NULL,
  `Image` longblob,
  PRIMARY KEY (`RowID`),
  UNIQUE KEY `Index 9` (`AccountNo`,`AccountType`,`OrganizationID`),
  KEY `FK_account_user` (`CreatedBy`),
  KEY `FK_account_user_2` (`LastUpdBy`),
  KEY `FK_account_contact` (`PrimaryContactID`),
  KEY `FK_account_contact_2` (`PrimaryRepID`),
  KEY `FK_account_organization` (`OrganizationID`),
  KEY `FK_account_address` (`PrimaryAddressID`),
  KEY `FK_account_account` (`ParentAccountID`),
  CONSTRAINT `FK_account_account` FOREIGN KEY (`ParentAccountID`) REFERENCES `account` (`RowID`),
  CONSTRAINT `FK_account_address` FOREIGN KEY (`PrimaryAddressID`) REFERENCES `address` (`RowID`),
  CONSTRAINT `FK_account_contact` FOREIGN KEY (`PrimaryContactID`) REFERENCES `contact` (`RowID`),
  CONSTRAINT `FK_account_contact_2` FOREIGN KEY (`PrimaryRepID`) REFERENCES `contact` (`RowID`),
  CONSTRAINT `FK_account_organization` FOREIGN KEY (`OrganizationID`) REFERENCES `organization` (`RowID`),
  CONSTRAINT `FK_account_user` FOREIGN KEY (`CreatedBy`) REFERENCES `user` (`RowID`),
  CONSTRAINT `FK_account_user_2` FOREIGN KEY (`LastUpdBy`) REFERENCES `user` (`RowID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
