/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `allowanceperday` (
  `RowID` int(10) NOT NULL AUTO_INCREMENT,
  `AllowanceItemID` int(10) DEFAULT NULL,
  `Date` date DEFAULT NULL,
  `Amount` decimal(15,4) NOT NULL DEFAULT 0.0000,
  PRIMARY KEY (`RowID`),
  KEY `FK_allowanceperday_allowanceitem` (`AllowanceItemID`),
  CONSTRAINT `FK_allowanceperday_allowanceitem` FOREIGN KEY (`AllowanceItemID`) REFERENCES `allowanceitem` (`RowID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
