/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

DROP TABLE IF EXISTS `cashoutleave`;
CREATE TABLE IF NOT EXISTS `cashoutleave` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `OrganizationID` int(11) NOT NULL,
  `EmployeeID` int(11) NOT NULL,
  `LeaveLedgerID` int(11) NOT NULL,
  `PaystubID` int(11) DEFAULT NULL,
  `PayPeriodID` int(11) NOT NULL,
  `LeaveHours` decimal(20,6) NOT NULL DEFAULT 0.000000,
  `Amount` decimal(20,6) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE KEY `Unique` (`OrganizationID`,`EmployeeID`,`LeaveLedgerID`,`PayPeriodID`) USING BTREE,
  KEY `FK_cashoutleave_paystub` (`PaystubID`),
  CONSTRAINT `FK_cashoutleave_paystub` FOREIGN KEY (`PaystubID`) REFERENCES `paystub` (`RowID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
