/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `division` (
  `RowID` int(10) NOT NULL AUTO_INCREMENT,
  `Name` varchar(100) DEFAULT NULL,
  `TradeName` varchar(100) DEFAULT NULL,
  `OrganizationID` int(10) DEFAULT NULL,
  `DivisionHeadID` int(10) DEFAULT NULL,
  `MainPhone` varchar(50) DEFAULT NULL,
  `FaxNumber` varchar(50) DEFAULT NULL,
  `BusinessAddress` varchar(1000) DEFAULT NULL,
  `ContactName` varchar(200) DEFAULT NULL,
  `EmailAddress` varchar(50) DEFAULT NULL,
  `AltEmailAddress` varchar(50) DEFAULT NULL,
  `AltPhone` varchar(50) DEFAULT NULL,
  `URL` varchar(50) DEFAULT NULL,
  `TINNo` varchar(50) DEFAULT NULL,
  `Created` datetime DEFAULT current_timestamp(),
  `CreatedBy` int(11) DEFAULT NULL,
  `ParentDivisionID` int(10) DEFAULT NULL,
  `LastUpd` datetime DEFAULT NULL ON UPDATE current_timestamp(),
  `LastUpdBy` int(11) DEFAULT NULL,
  `DivisionType` varchar(50) DEFAULT NULL COMMENT 'Department, Branch,',
  `GracePeriod` decimal(10,2) DEFAULT 0.00,
  `WorkDaysPerYear` int(11) DEFAULT 313,
  `PhHealthDeductSched` varchar(50) DEFAULT 'End of the month',
  `HDMFDeductSched` varchar(50) DEFAULT 'End of the month',
  `SSSDeductSched` varchar(50) DEFAULT 'End of the month',
  `WTaxDeductSched` varchar(50) DEFAULT 'End of the month',
  `DefaultVacationLeave` decimal(11,2) DEFAULT 40.00,
  `DefaultSickLeave` decimal(11,2) DEFAULT 40.00,
  `DefaultMaternityLeave` decimal(11,2) DEFAULT 40.00,
  `DefaultPaternityLeave` decimal(11,2) DEFAULT 40.00,
  `DefaultOtherLeave` decimal(11,2) DEFAULT 40.00,
  `PayFrequencyID` int(11) DEFAULT NULL,
  `PhHealthDeductSchedAgency` varchar(50) DEFAULT 'End of the month',
  `HDMFDeductSchedAgency` varchar(50) DEFAULT 'End of the month',
  `SSSDeductSchedAgency` varchar(50) DEFAULT 'End of the month',
  `WTaxDeductSchedAgency` varchar(50) DEFAULT 'End of the month',
  `DivisionUniqueID` int(11) DEFAULT 1,
  `MinimumWageAmount` decimal(11,2) DEFAULT 466.00,
  `AutomaticOvertimeFiling` tinyint(4) NOT NULL DEFAULT 0,
  `SSSDeductionWeekSchedule` varchar(50) DEFAULT 'End of the month',
  `PhilhealthDeductionWeekSchedule` varchar(50) DEFAULT 'End of the month',
  `PagIbigDeductionWeekSchedule` varchar(50) DEFAULT 'End of the month',
  `WithholdingTaxDeductionWeekSchedule` varchar(50) DEFAULT 'End of the month',
  `SSSDeductionWeekwithAgenSchedule` varchar(50) DEFAULT 'End of the month',
  `PhilhealthDeductionWeekwithAgenSchedule` varchar(50) DEFAULT 'End of the month',
  `PagIbigDeductionWeekwithAgenSchedule` varchar(50) DEFAULT 'End of the month',
  `WithholdingTaxDeductionWeekwithAgenSchedule` varchar(50) DEFAULT 'End of the month',
  PRIMARY KEY (`RowID`),
  UNIQUE KEY `Name` (`Name`,`OrganizationID`,`ParentDivisionID`),
  KEY `FK_organization_user` (`CreatedBy`),
  KEY `FK_organization_user_2` (`LastUpdBy`),
  KEY `FK_employeepreviousemployer_organization` (`OrganizationID`),
  KEY `FK_division_division` (`ParentDivisionID`),
  CONSTRAINT `FK_division_division` FOREIGN KEY (`ParentDivisionID`) REFERENCES `division` (`RowID`),
  CONSTRAINT `division_ibfk_1` FOREIGN KEY (`OrganizationID`) REFERENCES `organization` (`RowID`),
  CONSTRAINT `division_ibfk_2` FOREIGN KEY (`CreatedBy`) REFERENCES `user` (`RowID`),
  CONSTRAINT `division_ibfk_3` FOREIGN KEY (`LastUpdBy`) REFERENCES `user` (`RowID`),
  CONSTRAINT `division_ibfk_4` FOREIGN KEY (`CreatedBy`) REFERENCES `user` (`RowID`),
  CONSTRAINT `division_ibfk_5` FOREIGN KEY (`LastUpdBy`) REFERENCES `user` (`RowID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='This is the internal Company';

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
