/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `employee` (
  `RowID` int(10) NOT NULL AUTO_INCREMENT,
  `CreatedBy` int(10) DEFAULT NULL,
  `Created` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `LastUpdBy` int(10) DEFAULT NULL,
  `LastUpd` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `OrganizationID` int(10) DEFAULT NULL,
  `Salutation` varchar(50) DEFAULT NULL,
  `FirstName` varchar(100) DEFAULT NULL,
  `MiddleName` varchar(100) DEFAULT NULL,
  `LastName` varchar(100) DEFAULT NULL,
  `Surname` varchar(50) DEFAULT NULL,
  `EmployeeID` varchar(50) DEFAULT NULL,
  `TINNo` varchar(50) DEFAULT NULL,
  `SSSNo` varchar(50) DEFAULT NULL,
  `HDMFNo` varchar(50) DEFAULT NULL,
  `PhilHealthNo` varchar(50) DEFAULT NULL,
  `EmploymentStatus` varchar(50) DEFAULT NULL,
  `EmailAddress` varchar(50) DEFAULT NULL,
  `WorkPhone` varchar(50) DEFAULT NULL,
  `HomePhone` varchar(50) DEFAULT NULL,
  `MobilePhone` varchar(50) DEFAULT NULL,
  `HomeAddress` varchar(2000) DEFAULT NULL,
  `Nickname` varchar(50) DEFAULT NULL,
  `JobTitle` varchar(50) DEFAULT NULL,
  `Gender` varchar(50) DEFAULT NULL,
  `EmployeeType` varchar(50) DEFAULT NULL COMMENT 'Regular Exempt, Regular Non Exempt, Contractor',
  `MaritalStatus` varchar(50) DEFAULT NULL,
  `Birthdate` date DEFAULT NULL,
  `StartDate` date DEFAULT NULL,
  `TerminationDate` date DEFAULT NULL,
  `PositionID` int(11) DEFAULT NULL,
  `PayFrequencyID` int(11) DEFAULT NULL,
  `NoOfDependents` int(11) DEFAULT '0',
  `UndertimeOverride` varchar(1) DEFAULT '0',
  `OvertimeOverride` varchar(1) DEFAULT '0',
  `NewEmployeeFlag` varchar(1) DEFAULT '0',
  `LeaveBalance` decimal(10,2) DEFAULT '0.00',
  `SickLeaveBalance` decimal(10,2) DEFAULT '0.00',
  `MaternityLeaveBalance` decimal(10,2) DEFAULT '0.00',
  `OtherLeaveBalance` decimal(10,2) DEFAULT '0.00',
  `LeaveAllowance` decimal(10,2) DEFAULT '0.00',
  `SickLeaveAllowance` decimal(10,2) DEFAULT '0.00',
  `MaternityLeaveAllowance` decimal(10,2) DEFAULT '0.00',
  `OtherLeaveAllowance` decimal(10,2) DEFAULT '0.00',
  `Image` mediumblob,
  `LeavePerPayPeriod` decimal(10,2) DEFAULT '0.00',
  `SickLeavePerPayPeriod` decimal(10,2) DEFAULT '0.00',
  `MaternityLeavePerPayPeriod` decimal(10,2) DEFAULT '0.00',
  `OtherLeavePerPayPeriod` decimal(10,2) DEFAULT '0.00',
  `AlphaListExempted` char(1) DEFAULT '0',
  `WorkDaysPerYear` int(11) DEFAULT '313',
  `DayOfRest` char(1) DEFAULT '1',
  `ATMNo` varchar(50) DEFAULT '',
  `BankName` varchar(50) DEFAULT '',
  `CalcHoliday` char(1) DEFAULT 'Y',
  `CalcSpecialHoliday` char(1) DEFAULT 'Y',
  `CalcNightDiff` char(1) DEFAULT 'Y',
  `CalcNightDiffOT` char(1) DEFAULT 'Y',
  `CalcRestDay` char(1) DEFAULT 'Y',
  `CalcRestDayOT` char(1) DEFAULT 'Y',
  `DateRegularized` date DEFAULT NULL,
  `DateEvaluated` date DEFAULT NULL,
  `RevealInPayroll` char(50) DEFAULT '1',
  `LateGracePeriod` decimal(11,2) DEFAULT '0.00',
  `AgencyID` int(11) DEFAULT NULL,
  `OffsetBalance` decimal(11,2) DEFAULT '0.00',
  `BranchID` int(11) DEFAULT NULL COMMENT 'this required field for employee - Store Manager || Crew',
  `AreaID` int(11) DEFAULT NULL COMMENT 'this required field for employee - Area Manager',
  `MinimumOvertime` time DEFAULT '00:00:00',
  PRIMARY KEY (`RowID`),
  UNIQUE KEY `Index 2` (`OrganizationID`,`EmployeeID`),
  KEY `Index 3` (`FirstName`,`MiddleName`,`LastName`,`Salutation`),
  KEY `Index 4` (`TINNo`),
  KEY `Index 5` (`SSSNo`),
  KEY `FK_Employee_user` (`CreatedBy`),
  KEY `FK_Employee_user_2` (`LastUpdBy`),
  KEY `FK_Employee_payfrequency` (`PayFrequencyID`),
  KEY `FK_employee_branch` (`BranchID`),
  KEY `FK_employee_area` (`AreaID`),
  FULLTEXT KEY `FULLTEXT KEY` (`EmployeeID`,`FirstName`,`LastName`,`Nickname`),
  CONSTRAINT `FK_Employee_organization` FOREIGN KEY (`OrganizationID`) REFERENCES `organization` (`RowID`),
  CONSTRAINT `FK_Employee_payfrequency` FOREIGN KEY (`PayFrequencyID`) REFERENCES `payfrequency` (`RowID`),
  CONSTRAINT `FK_Employee_user` FOREIGN KEY (`CreatedBy`) REFERENCES `user` (`RowID`),
  CONSTRAINT `FK_Employee_user_2` FOREIGN KEY (`LastUpdBy`) REFERENCES `user` (`RowID`),
  CONSTRAINT `FK_employee_area` FOREIGN KEY (`AreaID`) REFERENCES `area` (`RowID`),
  CONSTRAINT `FK_employee_branch` FOREIGN KEY (`BranchID`) REFERENCES `branch` (`RowID`)
) ENGINE=InnoDB AUTO_INCREMENT=780 DEFAULT CHARSET=latin1 COMMENT='Employee Table';

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
