/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `employeeshiftbyday_secondary` (
  `OrganizationID` int(10) NOT NULL,
  `EmployeeID` int(10) DEFAULT NULL,
  `ShiftID` int(10) DEFAULT NULL,
  `NameOfDay` varchar(50) DEFAULT NULL,
  `SampleDate` date DEFAULT NULL,
  `NightShift` char(1) DEFAULT NULL,
  `RestDay` char(1) DEFAULT NULL,
  `IsEncodedByDay` char(1) DEFAULT '1',
  `OrderByValue` int(10) DEFAULT '0',
  `OriginDay` int(10) DEFAULT NULL,
  `UniqueShift` int(10) DEFAULT '0',
  UNIQUE KEY `OrganizationID` (`OrganizationID`,`EmployeeID`,`ShiftID`,`NameOfDay`,`SampleDate`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=COMPACT;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
