/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

DROP TABLE IF EXISTS `leavetenure`;
CREATE TABLE IF NOT EXISTS `leavetenure` (
  `LeaveResetId` int(11) NOT NULL,
  `OrdinalValue` int(11) NOT NULL,
  `Min` decimal(20,6) NOT NULL DEFAULT 0.000000,
  `Max` decimal(20,6) NOT NULL DEFAULT 0.000000,
  `VacationLeaveHours` decimal(20,6) NOT NULL DEFAULT 0.000000,
  `SickLeaveHours` decimal(20,6) NOT NULL DEFAULT 0.000000,
  `OthersLeaveHours` decimal(20,6) NOT NULL DEFAULT 0.000000,
  `ParentalLeaveHours` decimal(20,6) NOT NULL DEFAULT 0.000000,
  UNIQUE KEY `LeaveResetId` (`LeaveResetId`,`OrdinalValue`),
  CONSTRAINT `FK_leavetenure_leavereset` FOREIGN KEY (`LeaveResetId`) REFERENCES `leavereset` (`Id`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
