/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `order` (
  `RowID` int(10) NOT NULL AUTO_INCREMENT,
  `RelatedOrderId` int(10) DEFAULT NULL COMMENT 'Used to relate an order to the other order',
  `Created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `OrganizationID` int(11) NOT NULL COMMENT 'Internal Company',
  `OrderNumber` varchar(10) DEFAULT NULL COMMENT 'Order Number. Should be Editable, This is where we store the MRF#, DR#, PRS#, PL#, RR#',
  `CustomerName` varchar(200) DEFAULT NULL,
  `CustomerAddress` varchar(500) DEFAULT NULL,
  `ContactID` int(11) DEFAULT NULL COMMENT 'Contact associated to the Order. Links to Contact table.',
  `SupplierID` int(11) DEFAULT NULL,
  `QuoteID` int(11) DEFAULT NULL COMMENT 'Before becoming a Order, this started with a Quote. Links to Quote table',
  `OrderDate` datetime NOT NULL COMMENT 'Date of Order.',
  `Type` varchar(50) NOT NULL COMMENT 'Sales Order, Purchase Order',
  `TotalAmount` decimal(10,2) DEFAULT '0.00' COMMENT 'Total Amount Due of the Order',
  `TotalDownPayment` decimal(10,2) DEFAULT '0.00' COMMENT 'Total Downpayment',
  `TotalPayment` decimal(10,2) DEFAULT '0.00' COMMENT 'Total Paid so far',
  `TotalBalance` decimal(10,2) DEFAULT '0.00' COMMENT 'balance of the order',
  `Status` varchar(50) DEFAULT NULL COMMENT 'Open, Shipped, Cancelled, DR Returned, Approved for Inventory',
  `StatusAsOf` varchar(50) DEFAULT NULL COMMENT 'recorded when status changed',
  `InvoiceNo` int(11) DEFAULT NULL COMMENT 'Invoice Number of the Order',
  `Comments` varchar(2000) DEFAULT NULL,
  `LastUpd` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `CreatedBy` int(11) NOT NULL,
  `LastUpdBy` int(11) NOT NULL,
  `InventoryLocationID` int(11) DEFAULT NULL COMMENT 'Defines which branch is this order from.',
  `RelatedMRFId` int(11) DEFAULT NULL,
  `RelatedPRSId` int(11) DEFAULT NULL,
  `RelatedPLId` int(11) DEFAULT NULL,
  `PulloutControlNo` int(11) DEFAULT NULL,
  `RelatedRRId` int(11) DEFAULT NULL,
  `RelatedDRId` int(11) DEFAULT NULL,
  `RelatedPCId` int(11) DEFAULT NULL,
  `BranchFromID` int(11) DEFAULT NULL COMMENT 'used for Pullouts/Stock Transfer from one Branch to Another',
  `BranchToID` int(11) DEFAULT NULL COMMENT 'used for Pullouts/Stock Transfer from one Branch to Another',
  `ProductCategoryID` int(11) DEFAULT NULL,
  `ProductCategoryAltName` varchar(200) DEFAULT NULL,
  `ProductCatalogID` int(11) DEFAULT NULL,
  `ProductCatalogAltName` varchar(200) DEFAULT NULL,
  `Terms` decimal(10,2) DEFAULT NULL,
  PRIMARY KEY (`RowID`),
  UNIQUE KEY `Index 2` (`Type`,`OrderNumber`,`OrganizationID`),
  KEY `FK_order_order` (`RelatedOrderId`),
  KEY `FK_order_organization` (`OrganizationID`),
  KEY `FK_order_user` (`CreatedBy`),
  KEY `FK_order_user_2` (`LastUpdBy`),
  KEY `FK_order_leasequote` (`QuoteID`),
  KEY `FK_order_contact` (`ContactID`),
  KEY `FK_order_inventorylocation` (`InventoryLocationID`),
  KEY `FK_order_order_2` (`RelatedMRFId`),
  KEY `FK_order_order_3` (`RelatedPRSId`),
  KEY `FK_order_order_4` (`RelatedPLId`),
  KEY `FK_order_order_5` (`RelatedRRId`),
  KEY `FK_order_order_6` (`RelatedDRId`),
  KEY `FK_order_inventorylocation_2` (`BranchFromID`),
  KEY `FK_order_inventorylocation_3` (`BranchToID`),
  KEY `FK_order_order_7` (`RelatedPCId`),
  KEY `FK_order_account` (`SupplierID`),
  KEY `FK_order_category` (`ProductCategoryID`),
  CONSTRAINT `FK_order_account` FOREIGN KEY (`SupplierID`) REFERENCES `account` (`RowID`),
  CONSTRAINT `FK_order_category` FOREIGN KEY (`ProductCategoryID`) REFERENCES `category` (`RowID`),
  CONSTRAINT `FK_order_contact` FOREIGN KEY (`ContactID`) REFERENCES `contact` (`RowID`),
  CONSTRAINT `FK_order_inventorylocation` FOREIGN KEY (`InventoryLocationID`) REFERENCES `inventorylocation` (`RowID`),
  CONSTRAINT `FK_order_inventorylocation_2` FOREIGN KEY (`BranchFromID`) REFERENCES `inventorylocation` (`RowID`),
  CONSTRAINT `FK_order_inventorylocation_3` FOREIGN KEY (`BranchToID`) REFERENCES `inventorylocation` (`RowID`),
  CONSTRAINT `FK_order_leasequote` FOREIGN KEY (`QuoteID`) REFERENCES `quote` (`RowID`),
  CONSTRAINT `FK_order_order` FOREIGN KEY (`RelatedOrderId`) REFERENCES `order` (`RowID`),
  CONSTRAINT `FK_order_order_2` FOREIGN KEY (`RelatedMRFId`) REFERENCES `order` (`RowID`),
  CONSTRAINT `FK_order_order_3` FOREIGN KEY (`RelatedPRSId`) REFERENCES `order` (`RowID`),
  CONSTRAINT `FK_order_order_4` FOREIGN KEY (`RelatedPLId`) REFERENCES `order` (`RowID`),
  CONSTRAINT `FK_order_order_5` FOREIGN KEY (`RelatedRRId`) REFERENCES `order` (`RowID`),
  CONSTRAINT `FK_order_order_6` FOREIGN KEY (`RelatedDRId`) REFERENCES `order` (`RowID`),
  CONSTRAINT `FK_order_order_7` FOREIGN KEY (`RelatedPCId`) REFERENCES `order` (`RowID`),
  CONSTRAINT `FK_order_organization` FOREIGN KEY (`OrganizationID`) REFERENCES `organization` (`RowID`),
  CONSTRAINT `FK_order_user` FOREIGN KEY (`CreatedBy`) REFERENCES `user` (`RowID`),
  CONSTRAINT `FK_order_user_2` FOREIGN KEY (`LastUpdBy`) REFERENCES `user` (`RowID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='This is the table that holds all orders - Purchase Order/Requisition, Material Request, Sales Order, Service Order anything that has to do with Orders.  The differentiation is by the column "Type"';

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
