/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `paystub` (
  `RowID` int(10) NOT NULL AUTO_INCREMENT,
  `OrganizationID` int(10) NOT NULL,
  `Created` timestamp NOT NULL DEFAULT current_timestamp(),
  `CreatedBy` int(10) DEFAULT NULL,
  `LastUpd` datetime DEFAULT NULL ON UPDATE current_timestamp(),
  `LastUpdBy` int(10) DEFAULT NULL,
  `PayPeriodID` int(10) NOT NULL,
  `EmployeeID` int(10) NOT NULL,
  `PayFromDate` date DEFAULT NULL,
  `PayToDate` date DEFAULT NULL,
  `BasicHours` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `BasicPay` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `RegularHours` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `RegularPay` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `OvertimeHours` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `OvertimePay` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `NightDiffHours` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `NightDiffPay` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `NightDiffOvertimeHours` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `NightDiffOvertimePay` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `RestDayHours` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `RestDayPay` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `RestDayOTHours` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `RestDayOTPay` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `LeaveHours` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `LeavePay` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `SpecialHolidayHours` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `SpecialHolidayPay` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `SpecialHolidayOTHours` decimal(11,6) NOT NULL DEFAULT 0.000000,
  `SpecialHolidayOTPay` decimal(11,6) NOT NULL DEFAULT 0.000000,
  `RegularHolidayHours` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `RegularHolidayPay` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `RegularHolidayOTHours` decimal(11,6) NOT NULL DEFAULT 0.000000,
  `RegularHolidayOTPay` decimal(11,6) NOT NULL DEFAULT 0.000000,
  `HolidayPay` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `SpecialHolidayRestDayPay` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `SpecialHolidayRestDayOTHours` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `SpecialHolidayRestDayOTPay` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `SpecialHolidayRestDayNightDiffHours` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `SpecialHolidayRestDayNightDiffPay` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `SpecialHolidayRestDayNightDiffOTHours` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `SpecialHolidayRestDayNightDiffOTPay` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `RegularHolidayNightDiffHours` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `RegularHolidayNightDiffPay` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `RegularHolidayNightDiffOTHours` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `RegularHolidayNightDiffOTPay` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `RegularHolidayRestDayHours` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `RegularHolidayRestDayPay` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `RegularHolidayRestDayOTHours` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `RegularHolidayRestDayOTPay` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `RegularHolidayRestDayNightDiffHours` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `RegularHolidayRestDayNightDiffPay` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `RegularHolidayRestDayNightDiffOTHours` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `RegularHolidayRestDayNightDiffOTPay` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `LateHours` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `LateDeduction` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `UndertimeHours` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `UndertimeDeduction` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `AbsentHours` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `AbsenceDeduction` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `RestDayNightDiffHours` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `RestDayNightDiffPay` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `RestDayNightDiffOTHours` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `RestDayNightDiffOTPay` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `SpecialHolidayNightDiffHours` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `SpecialHolidayNightDiffPay` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `SpecialHolidayNightDiffOTHours` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `SpecialHolidayNightDiffOTPay` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `SpecialHolidayRestDayHours` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `WorkPay` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `TotalGrossSalary` decimal(10,2) NOT NULL DEFAULT 0.00,
  `TotalNetSalary` decimal(10,2) NOT NULL DEFAULT 0.00,
  `DeferredTaxableIncome` decimal(10,2) NOT NULL DEFAULT 0.00,
  `TotalTaxableSalary` decimal(10,2) NOT NULL DEFAULT 0.00,
  `TotalEmpSSS` decimal(10,2) NOT NULL DEFAULT 0.00,
  `TotalEmpWithholdingTax` decimal(10,2) NOT NULL DEFAULT 0.00,
  `TotalCompSSS` decimal(10,2) NOT NULL DEFAULT 0.00,
  `TotalEmpPhilhealth` decimal(10,2) NOT NULL DEFAULT 0.00,
  `TotalCompPhilhealth` decimal(10,2) NOT NULL DEFAULT 0.00,
  `TotalEmpHDMF` decimal(10,2) NOT NULL DEFAULT 0.00,
  `TotalCompHDMF` decimal(10,2) NOT NULL DEFAULT 0.00,
  `TotalVacationDaysLeft` decimal(10,2) NOT NULL DEFAULT 0.00,
  `TotalUndeclaredSalary` decimal(10,2) NOT NULL DEFAULT 0.00,
  `TotalLoans` decimal(10,2) NOT NULL DEFAULT 0.00,
  `TotalBonus` decimal(10,2) NOT NULL DEFAULT 0.00,
  `TotalAllowance` decimal(10,2) NOT NULL DEFAULT 0.00,
  `TotalTaxableAllowance` decimal(10,2) NOT NULL DEFAULT 0.00,
  `TotalAdjustments` decimal(10,2) NOT NULL DEFAULT 0.00,
  `ThirteenthMonthInclusion` tinyint(1) NOT NULL DEFAULT 0,
  `FirstTimeSalary` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`RowID`),
  UNIQUE KEY `AK_paystub_PayPeriodID_EmployeeID` (`PayPeriodID`,`EmployeeID`),
  KEY `FK_BaseTables_organization` (`OrganizationID`),
  KEY `FK_BaseTables_user` (`CreatedBy`),
  KEY `FK_BaseTables_user_2` (`LastUpdBy`),
  KEY `FK_paystub_employee` (`EmployeeID`),
  KEY `Index 9` (`PayToDate`,`PayFromDate`),
  CONSTRAINT `FK-paystub_user_LastUpdBy` FOREIGN KEY (`LastUpdBy`) REFERENCES `user` (`RowID`),
  CONSTRAINT `FK_paystub_employee_EmployeeID` FOREIGN KEY (`EmployeeID`) REFERENCES `employee` (`RowID`) ON DELETE CASCADE,
  CONSTRAINT `FK_paystub_organization_OrganizationID` FOREIGN KEY (`OrganizationID`) REFERENCES `organization` (`RowID`),
  CONSTRAINT `FK_paystub_payperiod_PayPeriodID` FOREIGN KEY (`PayPeriodID`) REFERENCES `payperiod` (`RowID`),
  CONSTRAINT `FK_paystub_user_CreatedBy` FOREIGN KEY (`CreatedBy`) REFERENCES `user` (`RowID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
