/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `product` (
  `RowID` int(10) NOT NULL AUTO_INCREMENT,
  `SupplierID` int(10) DEFAULT NULL,
  `Name` varchar(200) DEFAULT '0',
  `OrganizationID` int(11) NOT NULL DEFAULT '0',
  `Description` varchar(2000) DEFAULT '0' COMMENT 'description for the product',
  `PartNo` varchar(200) NOT NULL DEFAULT '0' COMMENT 'unique part number for this product',
  `Created` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `LastUpd` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `LastArrivedQty` int(11) DEFAULT NULL COMMENT 'This contains the summation of the quantities that arrived from last shipment (calculated when warehouse manager is entering rack/shelf/column',
  `CreatedBy` int(11) NOT NULL DEFAULT '0',
  `LastUpdBy` int(11) DEFAULT '0',
  `Category` varchar(50) DEFAULT NULL COMMENT 'e.g. Indoor Lights, Outdoor Lights, Toilet Bowls, Sinks (Ikhea calls this Classification)',
  `CategoryID` int(11) DEFAULT NULL,
  `AccountingAccountID` int(11) DEFAULT NULL,
  `Catalog` varchar(50) DEFAULT '0' COMMENT 'e.g. Lights, Bathroom,Walls',
  `Comments` varchar(2000) DEFAULT '0',
  `Status` varchar(50) DEFAULT NULL COMMENT 'Active, Inactive',
  `Fixed` tinyint(1) DEFAULT NULL,
  `UnitPrice` decimal(10,2) DEFAULT '0.00' COMMENT 'SuggestedRetailPrice',
  `VATPercent` decimal(10,2) DEFAULT '0.00' COMMENT 'VAT % of this item',
  `FirstBillFlag` char(1) DEFAULT NULL COMMENT 'Flag to Indicate if this item should be included in First Billing',
  `SecondBillFlag` char(1) DEFAULT NULL COMMENT 'Flag to Indicate if this item should be included in Second Billing',
  `ThirdBillFlag` char(1) DEFAULT NULL COMMENT 'Flag to Indicate if this item should be included in Third Billing',
  `PDCFlag` char(1) DEFAULT NULL COMMENT 'Flag to Indicate if this item should be included in PDC Billing',
  `MonthlyBIllFlag` char(1) DEFAULT NULL COMMENT 'Flag to Indicate if this item should be included in Monthly Billing',
  `PenaltyFlag` char(1) DEFAULT NULL COMMENT 'Flag to indicate if this item is a penalty so it can be calculated as part of late penalties',
  `WithholdingTaxPercent` decimal(10,2) DEFAULT '0.00' COMMENT 'Withholding Tax for the item',
  `CostPrice` decimal(10,2) DEFAULT '0.00' COMMENT 'Avg Cost from Supplier',
  `UnitOfMeasure` varchar(50) DEFAULT '0',
  `SKU` varchar(50) DEFAULT '0' COMMENT 'Stock Keeping Unit (for example, 2 suppliers - same item - the part # will be the same but the SKU will be different)',
  `Image` mediumblob,
  `LeadTime` int(10) DEFAULT NULL COMMENT 'Lead Time (in Days) for Product Delivery from Supplier',
  `BarCode` varchar(50) DEFAULT '0',
  `BusinessUnitID` int(11) DEFAULT '0' COMMENT 'The organization (Business Unit) for which this product belongs to',
  `LastRcvdFromShipmentDate` date DEFAULT NULL COMMENT 'when this product was last received from Shipment',
  `LastRcvdFromShipmentCount` int(11) DEFAULT NULL COMMENT 'how many of this item was received from last shipment',
  `TotalShipmentCount` int(11) DEFAULT NULL,
  `BookPageNo` varchar(10) DEFAULT '0',
  `BrandName` varchar(50) DEFAULT '0',
  `LastPurchaseDate` date DEFAULT NULL COMMENT 'Date on which this item is last purchased',
  `LastSoldDate` date DEFAULT NULL COMMENT 'Date on which this item is last sold (to be able to determine aging)',
  `LastSoldCount` int(11) DEFAULT '0',
  `ReOrderPoint` int(10) DEFAULT '0',
  `AllocateBelowSafetyFlag` char(1) DEFAULT '0' COMMENT 'If Allocation is below Safety Levels (re-Order Point)',
  `Strength` varchar(30) DEFAULT NULL COMMENT 'Strength of Product (Fast Moving, Slow Moving)',
  `UnitsBackordered` int(10) DEFAULT NULL COMMENT '# of units on Backorder',
  `UnitsBackorderAsOf` datetime DEFAULT NULL COMMENT 'Date for which units on backorder were reported',
  `DateLastInventoryCount` datetime DEFAULT NULL COMMENT 'Date of which the main warehouse''s inventory was counted for this item',
  `TaxVAT` decimal(10,2) DEFAULT NULL,
  `WithholdingTax` decimal(10,2) DEFAULT NULL,
  `COAId` int(11) DEFAULT NULL,
  `ActiveData` char(1) DEFAULT '1',
  PRIMARY KEY (`RowID`),
  UNIQUE KEY `Index 5` (`PartNo`,`OrganizationID`,`CategoryID`),
  KEY `FK_product_user` (`CreatedBy`),
  KEY `FK_product_user_2` (`LastUpdBy`),
  KEY `FK_product_account` (`SupplierID`),
  KEY `Index 7` (`OrganizationID`,`Name`),
  KEY `FK_product_category` (`CategoryID`),
  KEY `FK_product_chartofaccounts` (`COAId`),
  CONSTRAINT `FK_product_account` FOREIGN KEY (`SupplierID`) REFERENCES `account` (`RowID`),
  CONSTRAINT `FK_product_category` FOREIGN KEY (`CategoryID`) REFERENCES `category` (`RowID`),
  CONSTRAINT `FK_product_chartofaccounts` FOREIGN KEY (`COAId`) REFERENCES `chartofaccounts` (`RowID`),
  CONSTRAINT `FK_product_organization` FOREIGN KEY (`OrganizationID`) REFERENCES `organization` (`RowID`),
  CONSTRAINT `FK_product_user` FOREIGN KEY (`CreatedBy`) REFERENCES `user` (`RowID`),
  CONSTRAINT `FK_product_user_2` FOREIGN KEY (`LastUpdBy`) REFERENCES `user` (`RowID`)
) ENGINE=InnoDB AUTO_INCREMENT=2193 DEFAULT CHARSET=latin1 COMMENT='Products/Material Items table';

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
