/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `rolepermission` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `RoleId` binary(16) NOT NULL,
  `PermissionId` int(11) NOT NULL,
  `Read` tinyint(1) NOT NULL DEFAULT 0,
  `Create` tinyint(1) NOT NULL DEFAULT 0,
  `Update` tinyint(1) NOT NULL DEFAULT 0,
  `Delete` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`Id`) USING BTREE,
  UNIQUE KEY `RoleId_PermissionId` (`RoleId`,`PermissionId`) USING BTREE,
  KEY `FK_rolepermission_permission` (`PermissionId`) USING BTREE,
  CONSTRAINT `FK_rolepermission_aspnetroles` FOREIGN KEY (`RoleId`) REFERENCES `aspnetroles` (`Id`),
  CONSTRAINT `FK_rolepermission_permission` FOREIGN KEY (`PermissionId`) REFERENCES `permission` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
