/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP TRIGGER IF EXISTS `AFTDEL_employeeoffset`;
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `AFTDEL_employeeoffset` AFTER DELETE ON `employeeoffset` FOR EACH ROW BEGIN

DECLARE sec_per_hour INT(11) DEFAULT 3600; # 60 seconds times 60 minutes

DECLARE offset_hrs DECIMAL(11, 2);

SET offset_hrs = TIMESTAMPDIFF(SECOND
                               , CONCAT_DATETIME(OLD.StartDate, OLD.StartTime)
										 , CONCAT_DATETIME(ADDDATE(OLD.StartDate, INTERVAL IS_TIMERANGE_REACHTOMORROW(OLD.StartTime, OLD.EndTime) DAY), OLD.EndTime)) / sec_per_hour;


UPDATE employee
SET OffsetBalance = (OffsetBalance - IFNULL(offset_hrs, 0))
WHERE RowID=OLD.EmployeeID
AND OLD.`Status` = 'Approved';

SET GLOBAL event_scheduler = ON;

END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
