/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP PROCEDURE IF EXISTS `AUTOINS_leaveledger`;
DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `AUTOINS_leaveledger`(IN `og_rowid` INT, IN `e_rowid` INT, IN `user_rowid` INT)
    DETERMINISTIC
BEGIN

DECLARE leave_type TEXT DEFAULT 'Leave type';

INSERT INTO leaveledger (OrganizationID, Created, CreatedBy, EmployeeID, ProductID, LastTransactionID)
SELECT p.OrganizationID
, CURRENT_TIMESTAMP()
, user_rowid
, e_rowid
, p.RowID
, NULL
FROM product p
WHERE p.OrganizationID=og_rowid
AND p.`Category`=leave_type
ON DUPLICATE KEY UPDATE
LastUpd = CURRENT_TIMESTAMP(), LastUpdBy = user_rowid
;

END//
DELIMITER ;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
