/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP TRIGGER IF EXISTS `BEFUPD_paystub`;
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `BEFUPD_paystub` BEFORE UPDATE ON `paystub` FOR EACH ROW BEGIN



SET NEW.FirstTimeSalary = (SELECT (StartDate BETWEEN NEW.PayFromDate AND NEW.PayToDate) FROM employee WHERE RowID=NEW.EmployeeID AND OrganizationID=NEW.OrganizationID);

SET @total_adj = 0.00;

SELECT SUM(adj.PayAmount)
FROM paystubadjustment adj
WHERE adj.PayStubID=NEW.RowID
AND adj.OrganizationID=NEW.OrganizationID
INTO @total_adj;

IF IFNULL(@total_adj, 0) != 0 THEN
	SET NEW.TotalNetSalary = (NEW.TotalNetSalary + IFNULL(@total_adj, 0));
END IF;

END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
