/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP TRIGGER IF EXISTS `BEFUPD_employeetimeentrydetails`;
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `BEFUPD_employeetimeentrydetails` BEFORE UPDATE ON `employeetimeentrydetails` FOR EACH ROW BEGIN

DECLARE anyint INT(11);

DECLARE $dateIn DATE;
DECLARE $dateOut DATE;

SET NEW.TimeIn = PROPER_24HOUR(NEW.TimeIn);
SET NEW.TimeOut = PROPER_24HOUR(NEW.TimeOut);

SET $dateIn = NEW.`Date`;
SET $dateOut = NEW.`Date`;

IF NEW.TimeIn IS NOT NULL AND NEW.TimeOut IS NOT NULL THEN

    IF NEW.TimeIn > NEW.TimeOut THEN

        SET $dateIn = NEW.`Date`;
        SET $dateOut = ADDDATE(NEW.`Date`, INTERVAL 1 DAY);

    END IF;

END IF;

IF NEW.TimeStampIn IS NULL THEN
    SET NEW.TimeStampIn = TIMESTAMP($dateIn, NEW.TimeIn);
END IF;

IF NEW.TimeStampOut IS NULL THEN
    SET NEW.TimeStampOut = TIMESTAMP($dateOut, NEW.TimeOut);
END IF;

END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
