/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP FUNCTION IF EXISTS `GetListOfValueOrDefault`;
DELIMITER //
CREATE DEFINER=`root`@`localhost` FUNCTION `GetListOfValueOrDefault`(
	`$Type` VARCHAR(50),
	`$LIC` VARCHAR(50),
	`$Default` VARCHAR(50)
) RETURNS varchar(50) CHARSET utf8
BEGIN

    DECLARE $displayValue VARCHAR(50);

    SELECT l.DisplayValue
    FROM listofval l
    WHERE l.`Type` = $Type AND
        l.LIC = $LIC
    LIMIT 1
    INTO $displayValue;
    
    RETURN IF(ISNULL($displayValue), $Default, $displayValue);

END//
DELIMITER ;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
