/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP FUNCTION IF EXISTS `PROPER_24HOUR`;
DELIMITER //
CREATE DEFINER=`root`@`localhost` FUNCTION `PROPER_24HOUR`(`param_time` TIME) RETURNS time
    DETERMINISTIC
BEGIN

DECLARE hour24 INT(11) DEFAULT 24;

DECLARE oclock12am VARCHAR(50) DEFAULT '00:%i:%s';

DECLARE return_value TIME;

IF HOUR(param_time) = hour24 THEN

	SET return_value = TIME_FORMAT(param_time, oclock12am);
ELSE
	
	SET return_value = param_time;
END IF;

RETURN return_value;

END//
DELIMITER ;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
