/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP PROCEDURE IF EXISTS `VIEW_branch`;
DELIMITER //
CREATE DEFINER=`root`@`127.0.0.1` PROCEDURE `VIEW_branch`(IN `OrganizID` INT, IN `PageNumber` INT, IN `br_RowID` VARCHAR(150))
    DETERMINISTIC
BEGIN

IF IFNULL(br_RowID,0) = 0 THEN

    SELECT
    RowID
    ,BranchCode
    ,BranchName
    FROM branch
    WHERE OrganizationID=OrganizID
    LIMIT PageNumber, 10;

ELSE

    SELECT
    RowID
    ,BranchCode
    ,BranchName
    FROM branch
    WHERE OrganizationID=OrganizID
    AND LOCATE(BranchCode,br_RowID) > 0
    LIMIT PageNumber, 10;

END IF;

END//
DELIMITER ;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
