Public Class GeneratePaystub
    Sub New(employees As DataTable,
            _isEndOfMonth As String,
            salaries As DataTable,
            loans As DataTable,
            bonuses As DataTable,
            dailyAllowances As DataTable,
            monthlyAllowances As DataTable,
            oneTimeAllowances As DataTable,
            semiMonthlyAllowances As DataTable,
            weeklyAllowances As DataTable,
            noTaxDailyAllowances As DataTable,
            noTaxMonthlyAllowances As DataTable,
            noTaxOneTimeAllowances As DataTable,
            noTaxSemiMonthlyAllowances As DataTable,
            noTaxWeeklyAllowances As DataTable,
            dailyBonuses As DataTable,
            monthlyBonuses As DataTable,
            oneTimeBonuses As DataTable,
            semiMonthlyBonuses As DataTable,
            weeklyBonuses As DataTable,
            noTaxDailyBonuses As DataTable,
            noTaxMonthlyBonuses As DataTable,
            noTaxOneTimeBonuses As DataTable,
            noTaxSemiMonthlyBonuses As DataTable,
            noTaxWeeklyBonuses As DataTable,
            _numofdaypresent As DataTable,
            timeEntries As DataTable,
            _dtemployeefirsttimesalary As DataTable,
            _prev_empTimeEntry As DataTable,
            _VeryFirstPayPeriodIDOfThisYear As Object,
            _withthirteenthmonthpay As SByte,
            Optional pay_stub_frm As PayStub = Nothing)
    End Sub
End Class
